//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress17EmptyWebForms.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iepcdbEntities : DbContext
    {
        public iepcdbEntities()
            : base("data source=NIKMORO-PC\\SQLEXPRESS;initial catalog=iepcdb;user id=sa;password=nikmoro;MultipleActiveResultSets=True")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DigitosMinistracion> DigitosMinistracions { get; set; }
        public virtual DbSet<ObjetosGastoCategoria> ObjetosGastoCategorias { get; set; }
        public virtual DbSet<ProgramasFondo> ProgramasFondoes { get; set; }
        public virtual DbSet<ProyectosOrigenAsignacion> ProyectosOrigenAsignacions { get; set; }
        public virtual DbSet<SubFuentesFinanciamiento> SubFuentesFinanciamientoes { get; set; }
        public virtual DbSet<SubSubFuncion> SubSubFuncions { get; set; }
        public virtual DbSet<TiposRecurso> TiposRecursoes { get; set; }
    }
}
